#####################################################################
#
#   CMakeLists.txt
#
#   Main CMake configuration script.
#
#####################################################################

# Preamble
# -------------------------------------------------------------------

cmake_minimum_required(VERSION 3.1)
project(toobad4ml
    VERSION 0.0.1
    DESCRIPTION "A tool for extracting characteristics of Buffer Overflow \
    vulnerabilities written in C code in order to further analyze them \
    with Machine Learning techniques"
    LANGUAGES CXX
)

# Project wide setup
# -------------------------------------------------------------------

# disable in-source builds
if ("${CMAKE_SOURCE_DIR}" STREQUAL "${CMAKE_BINARY_DIR}")
    message(FATAL_ERROR
        "This project does not allow in-source builds. Please remove "
        "CMakeCache.txt and CMakeFiles, then create a separate directory for "
        "the build files."
    )
endif()

# default build type
if (NOT CMAKE_BUILD_TYPE)
    set(CMAKE_BUILD_TYPE Debug
        CACHE STRING "Default build type set to Debug" FORCE)
endif()

# project directories
set(CMAKE_RUNTIME_OUTPUT_DIRECTORY "${CMAKE_CURRENT_SOURCE_DIR}/bin")
set(CMAKE_LIBRARY_OUTPUT_DIRECTORY "${CMAKE_CURRENT_SOURCE_DIR}/lib")
set(CMAKE_ARCHIVE_OUTPUT_DIRECTORY "${CMAKE_CURRENT_SOURCE_DIR}/lib")

# additional modules
list(APPEND CMAKE_MODULE_PATH   # custom scripts
                                "${CMAKE_CURRENT_SOURCE_DIR}/cmake"
                                # conan's autogenerated scripts
                                "${CMAKE_BINARY_DIR}"
)

# user options
option(TOOBAD4ML_ENABLE_TESTING "Build tests" OFF)
option(TOOBAD4ML_FORCE_CONAN    "Force use dependencies from Conan" OFF)
option(TOOBAD4ML_GENERATE_DOCS  "Build documentation" OFF)

# Dependencies
# -------------------------------------------------------------------

include(ClangLibTooling)

# Main build targets
# -------------------------------------------------------------------

# source code
add_subdirectory(src)

# test suite
if (TOOBAD4ML_ENABLE_TESTING)
    enable_testing()
    add_subdirectory(tests)
endif(TOOBAD4ML_ENABLE_TESTING)

# documentation
if (TOOBAD4ML_GENERATE_DOCS)
    add_subdirectory(docs)
endif (TOOBAD4ML_GENERATE_DOCS)